version: '3.8'

services:
  php:
    build: .
    depends_on:
      - mysql
    volumes:
      - .:/app:delegated
    working_dir: /app
    environment:
      PHP_ENV: development
    user: "${UID}:${GID}"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app 
    depends_on:
      - php

  composer:
    image: composer:2
    volumes:
      - .:/app 
    working_dir: /app
    environment:
      COMPOSER_HOME: /tmp/composer

  # MYSQL

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}  # Пароль для root
      MYSQL_DATABASE: ${DB_NAME:-rift}          # Создаёт БД при старте
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD:-root}
    depends_on:
      - mysql

  # POSTGRES

  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: ${DB_USER:-postgres}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
  #     POSTGRES_DB: ${DB_NAME:-rift}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 8082:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD:-admin}
  #   depends_on:
  #     - postgres

volumes:
  mysql_data:
  postgres_data:

