version: '3.8'

services:
  php:
    build: .
    volumes:
      - .:/app  # Монтируем ВЕСЬ проект (чтобы composer.json был доступен)
    working_dir: /app
    environment:
      PHP_ENV: development

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app  # Весь проект для nginx
    depends_on:
      - php

  composer:
    image: composer:2
    volumes:
      - .:/app  # Полный доступ к проекту
    working_dir: /app
    environment:
      COMPOSER_HOME: /tmp/composer

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-rift}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: